### ISSUE TITLE
提交的代码pullrequests 没给原因，直接就关闭了，不理解

### ISSUE THREAD

**Issue by 52lemon** [tomoncle/flaskapp#11]
提交的代码pullrequests 没给原因，直接就关闭了，不理解

**Comment by tomoncle** [comment]
对于 #10 这个PR未合并，没有给出解释，深表歉意，是我疏忽！

原因：配置文件中我不想携带用户的个人连接信息（即便是测试数据，因为测试数据中有时也会使用外网IP，开放代码更是如此），所以希望尽量使用的环境变量，详情见[Celery 配置](https://github.com/tomoncle/flaskapp/pull/10/commits/557fbb57df2037e9642ad06758dcb600f240cbd6#diff-117426151e93a626f8b46bfdb3a95b3f4a62e5f4dd6e65975a7c50759bf04482L40),  其他没有问题。

如果可以，希望reset此次提交，重新提交PR
